import React from "react";
import { Link } from 'react-router-dom';
import Nav from "./Nav";
import Footer from "./Footer";

export default function Legal() {
  return (
    <div className="min-h-screen bg-[#101012] text-[#F4F4F9] relative">
      {/* Subtle grid background */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          backgroundImage:
            "linear-gradient(to right, rgba(255,255,255,0.04) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.04) 1px, transparent 1px)",
          backgroundSize: "44px 44px",
        }}
      />
      <div className="relative">
        <Nav />
        <div className="max-w-4xl mx-auto px-6 py-20 pt-32">
        <h1 className="font-mono text-[12px] tracking-[0.3em] uppercase text-[#ccff00] mb-8">
          Legal Information
        </h1>
        
        <div className="space-y-16">
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-[#F4F4F9]">Terms & Conditions</h2>
            <div className="text-[#8E8E93] leading-relaxed space-y-8">
              <p className="font-mono text-[11px] tracking-[0.2em] uppercase text-[#8E8E93]">
                Last updated: September 22, 2026
              </p>

              <p>
                These Terms & Conditions govern your use of RaceSense App ("RaceSense", "we", "us", or "our"), a mobile application for karting lap analysis and coaching. RaceSense App is a mobile software application and is not affiliated with RaceSense tyre gauges, Fastmate Racing, or Swimovate Limited.
              </p>

              <p>
                By accessing or using RaceSense App, you agree to these Terms. If you do not agree with them, you should not use the service.
              </p>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">1. The Service</h3>
                <p>
                  RaceSense App provides mobile software designed to assist karting drivers by presenting lap time analysis and generating real-time voice coaching callouts.
                </p>
                <p>
                  The service may use information such as:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>lap times;</li>
                  <li>sector splits;</li>
                  <li>gaps to other drivers;</li>
                  <li>session information;</li>
                  <li>GPS location data; and</li>
                  <li>device audio for voice callouts.</li>
                </ul>
                <p>
                  Features may change, be added, removed, or temporarily unavailable without notice.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">2. Not a Substitute for Driver Judgement</h3>
                <p>
                  RaceSense App is an assistance tool only.
                </p>
                <p>
                  Callouts, recommendations, alerts and other information generated by the service may be delayed, incomplete, inaccurate or incorrect.
                </p>
                <p>
                  You remain solely responsible for controlling your vehicle, assessing the track and surrounding conditions, and making decisions while driving.
                </p>
                <p>
                  Never rely solely on RaceSense App for safety-critical decisions.
                </p>
                <p>
                  You should always follow the rules and instructions of the relevant circuit, event organiser, governing body and race officials.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">3. Device Requirements</h3>
                <p>
                  RaceSense App requires a compatible Android smartphone with audio capabilities.
                </p>
                <p>
                  The app uses your device's GPS, audio system, and other sensors. You are responsible for ensuring your device is properly charged and secured while driving.
                </p>
                <p>
                  We do not guarantee compatibility with all devices or Android versions.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">4. Availability</h3>
                <p>
                  We aim to keep RaceSense App available and reliable, but we do not guarantee uninterrupted access.
                </p>
                <p>
                  The service may be unavailable because of:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>maintenance;</li>
                  <li>software updates;</li>
                  <li>network failures;</li>
                  <li>device compatibility issues;</li>
                  <li>technical failures; or</li>
                  <li>circumstances outside our reasonable control.</li>
                </ul>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">5. Intellectual Property</h3>
                <p>
                  The RaceSense App software, branding, interface, original content, algorithms and associated materials are owned by or licensed to RaceSense App unless otherwise stated.
                </p>
                <p>
                  You may not copy, reproduce, modify, redistribute, reverse engineer, resell or commercially exploit RaceSense App without our permission, except where permitted by law.
                </p>
                <p>
                  RaceSense App is not affiliated with RaceSense tyre gauges, Fastmate Racing, or Swimovate Limited.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">6. Acceptable Use</h3>
                <p>
                  You must not use RaceSense App to:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>interfere with the operation of the service;</li>
                  <li>circumvent technical restrictions;</li>
                  <li>attempt to gain unauthorised access;</li>
                  <li>overload or disrupt our systems;</li>
                  <li>reproduce or redistribute the service without permission;</li>
                  <li>use automated systems to abuse the service; or</li>
                  <li>use the service for unlawful purposes.</li>
                </ul>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">7. Changes to the Service</h3>
                <p>
                  We may modify, suspend or discontinue any part of RaceSense App at any time.
                </p>
                <p>
                  We may also update these Terms when necessary. The latest version will be published on this page.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">8. Limitation of Liability</h3>
                <p>
                  To the maximum extent permitted by law, RaceSense App and its developers shall not be responsible for losses arising from reliance on inaccurate, delayed or unavailable race information or callouts.
                </p>
                <p>
                  Nothing in these Terms excludes or limits liability where doing so would be unlawful, including liability that cannot legally be excluded under applicable UK law.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">9. Governing Law</h3>
                <p>
                  These Terms are governed by the laws of England and Wales.
                </p>
                <p>
                  Any disputes relating to the service will be subject to the jurisdiction of the courts of England and Wales, unless applicable law requires otherwise.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">10. Contact</h3>
                <p>
                  For questions regarding these Terms, please contact:
                </p>
                <div className="mt-4 space-y-2">
                  <p className="text-[#F4F4F9]">RaceSense App</p>
                  <p className="text-[#F4F4F9]">Email: harryjbedford25@gmail.com</p>
                </div>
              </div>
            </div>
          </section>

          <section className="pt-8 border-t border-white/10">
            <h2 className="text-2xl font-semibold mb-4 text-[#F4F4F9]">Privacy Policy</h2>
            <div className="text-[#8E8E93] leading-relaxed space-y-8">
              <p className="font-mono text-[11px] tracking-[0.2em] uppercase text-[#8E8E93]">
                Last updated: September 22, 2026
              </p>

              <p>
                This Privacy Policy explains how RaceSense App collects, uses and protects personal information.
              </p>

              <p>
                The UK Information Commissioner's Office recommends that privacy notices clearly explain what personal information is collected, why it is used, how long it is retained and who it is shared with.
              </p>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">1. Who We Are</h3>
                <p>
                  RaceSense App is a mobile application for karting lap analysis and coaching.
                </p>
                <p>
                  For privacy-related enquiries:
                </p>
                <p className="text-[#ccff00]">Email: harryjbedford25@gmail.com</p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">2. Information We May Collect</h3>
                <p>
                  Depending on how you use the service, we may collect:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>email address;</li>
                  <li>account information;</li>
                  <li>race or session information;</li>
                  <li>device information;</li>
                  <li>GPS location data;</li>
                  <li>IP address;</li>
                  <li>error and diagnostic information;</li>
                  <li>usage information; and</li>
                  <li>information you voluntarily provide to us.</li>
                </ul>
                <p>
                  We will only collect information that is reasonably necessary to operate, maintain and improve the service.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">3. Race and Performance Data</h3>
                <p>
                  RaceSense App may process racing information including lap times, sector splits, and performance data.
                </p>
                <p>
                  This may include information such as:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>lap times;</li>
                  <li>sector performance;</li>
                  <li>gaps between drivers;</li>
                  <li>session information; and</li>
                  <li>GPS track data.</li>
                </ul>
                <p>
                  Where such information relates to an identifiable individual, it may constitute personal data under UK data protection law.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">4. How We Use Information</h3>
                <p>
                  We may use information to:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>provide the RaceSense App service;</li>
                  <li>generate voice coaching callouts;</li>
                  <li>maintain accounts;</li>
                  <li>diagnose technical problems;</li>
                  <li>improve the service;</li>
                  <li>prevent abuse;</li>
                  <li>maintain security;</li>
                  <li>understand service usage; and</li>
                  <li>respond to support enquiries.</li>
                </ul>
                <p>
                  We will not sell personal information to third parties.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">5. Legal Basis</h3>
                <p>
                  Where UK GDPR applies, we will process personal data using an appropriate lawful basis, which may include:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>performance of a contract;</li>
                  <li>legitimate interests;</li>
                  <li>consent; or</li>
                  <li>compliance with a legal obligation.</li>
                </ul>
                <p>
                  The appropriate basis depends on the particular processing activity.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">6. Data Retention</h3>
                <p>
                  We will retain personal information only for as long as reasonably necessary for the purpose for which it was collected, unless a longer period is required by law.
                </p>
                <p>
                  Specific retention periods may vary depending on the type of information.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">7. Data Sharing</h3>
                <p>
                  We may use trusted third-party service providers to operate parts of RaceSense App, such as hosting, authentication, analytics, error monitoring or communications.
                </p>
                <p>
                  Where third parties process personal data on our behalf, we will take reasonable steps to ensure that appropriate contractual and security arrangements are in place.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">8. Security</h3>
                <p>
                  We take reasonable technical and organisational measures to protect personal information against unauthorised access, loss, misuse or disclosure.
                </p>
                <p>
                  However, no internet service can guarantee absolute security.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">9. Your Rights</h3>
                <p>
                  Depending on the circumstances, you may have rights under UK data protection law including the right to:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>access your personal information;</li>
                  <li>request correction;</li>
                  <li>request deletion;</li>
                  <li>restrict processing;</li>
                  <li>object to certain processing;</li>
                  <li>withdraw consent where processing relies on consent; and</li>
                  <li>request data portability.</li>
                </ul>
                <p>
                  More information about privacy rights is available from the Information Commissioner's Office.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">10. Complaints</h3>
                <p>
                  If you have concerns about how we process your personal information, please contact us first at harryjbedford25@gmail.com.
                </p>
                <p>
                  You may also complain to the UK's data protection regulator, the Information Commissioner's Office.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">11. Changes</h3>
                <p>
                  We may update this Privacy Policy from time to time. The latest version will always be published on this page.
                </p>
              </div>
            </div>
          </section>

          <section className="pt-8 border-t border-white/10">
            <h2 className="text-2xl font-semibold mb-4 text-[#F4F4F9]">Cookie Policy</h2>
            <div className="text-[#8E8E93] leading-relaxed space-y-8">
              <p className="font-mono text-[11px] tracking-[0.2em] uppercase text-[#8E8E93]">
                Last updated: September 22, 2026
              </p>

              <p>
                This Cookie Policy explains how RaceSense App uses cookies and similar technologies.
              </p>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">1. What Are Cookies</h3>
                <p>
                  Cookies are small text files that are stored on your device when you visit our website or use our app. They help us provide you with a better experience and enable certain functionality.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">2. How We Use Cookies</h3>
                <p>
                  We use cookies for the following purposes:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>Essential cookies: Required for the app to function properly</li>
                  <li>Performance cookies: Help us understand how the app is used</li>
                  <li>Functionality cookies: Remember your preferences and settings</li>
                </ul>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">3. Managing Cookies</h3>
                <p>
                  You can control and manage cookies through your device settings. However, please note that disabling essential cookies may affect the functionality of the app.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">4. Third-Party Cookies</h3>
                <p>
                  We may use third-party services that use cookies, such as analytics providers. These third parties have their own privacy policies and we encourage you to review them.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">5. Updates</h3>
                <p>
                  We may update this Cookie Policy from time to time. The latest version will always be published on this page.
                </p>
              </div>
            </div>
          </section>

          <section className="pt-8 border-t border-white/10">
            <h2 className="text-2xl font-semibold mb-4 text-[#F4F4F9]">Disclaimers</h2>
            <div className="text-[#8E8E93] leading-relaxed space-y-8">
              <p className="font-mono text-[11px] tracking-[0.2em] uppercase text-[#8E8E93]">
                Last updated: September 22, 2026
              </p>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">Product Disclaimer</h3>
                <p>
                  RaceSense App is provided "as is" without warranties of any kind, either express or implied. We do not guarantee that the app will be error-free, uninterrupted, or that any defects will be corrected.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">Safety Disclaimer</h3>
                <p>
                  RaceSense App is not a safety device and should not be relied upon for safety-critical decisions. Always maintain proper situational awareness and follow all safety protocols while driving.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">Accuracy Disclaimer</h3>
                <p>
                  While we strive for accuracy, lap times, GPS data, and other information provided by the app may not be completely accurate or reliable. Verify critical information through official timing systems when available.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">Brand Disclaimer</h3>
                <p>
                  RaceSense App is a mobile software application and is not affiliated with, connected to, or related to RaceSense tyre gauges, Fastmate Racing, or Swimovate Limited. We are separate companies with different products.
                </p>
              </div>
            </div>
          </section>
        </div>
      </div>
      <Footer />
      </div>
    </div>
  );
}