import React from "react";
import Nav from "./Nav";
import Footer from "./Footer";

export default function Legal() {
  return (
    <div className="min-h-screen bg-[#0A0A0C] text-[#F4F4F9]">
      <Nav />
      <div className="max-w-4xl mx-auto px-6 py-20 pt-32">
        <h1 className="font-mono text-[12px] tracking-[0.3em] uppercase text-[#D2FF00] mb-8">
          Legal Information
        </h1>
        
        <div className="space-y-16">
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-[#F4F4F9]">Terms & Conditions</h2>
            <div className="text-[#8E8E93] leading-relaxed space-y-8">
              <p className="font-mono text-[11px] tracking-[0.2em] uppercase text-[#8E8E93]">
                Last updated: 25 August 2026
              </p>

              <p>
                These Terms & Conditions govern your use of My Race Engineer ("My Race Engineer", "we", "us", or "our"), a racing support application developed by Samuel Williams and Harry Bedford.
              </p>

              <p>
                By accessing or using My Race Engineer, you agree to these Terms. If you do not agree with them, you should not use the service.
              </p>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">1. The Service</h3>
                <p>
                  My Race Engineer provides software designed to assist drivers by presenting racing information and generating text-to-speech race engineer callouts.
                </p>
                <p>
                  The service may use information such as:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>live timing information;</li>
                  <li>lap times;</li>
                  <li>race position;</li>
                  <li>gaps to other drivers;</li>
                  <li>session information; and</li>
                  <li>other information available through supported timing systems.</li>
                </ul>
                <p>
                  Features may change, be added, removed, or temporarily unavailable without notice.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">2. Not a Substitute for Driver Judgement</h3>
                <p>
                  My Race Engineer is an assistance tool only.
                </p>
                <p>
                  Callouts, recommendations, alerts and other information generated by the service may be delayed, incomplete, inaccurate or incorrect.
                </p>
                <p>
                  You remain solely responsible for controlling your vehicle, assessing the track and surrounding conditions, and making decisions while driving.
                </p>
                <p>
                  Never rely solely on My Race Engineer for safety-critical decisions.
                </p>
                <p>
                  You should always follow the rules and instructions of the relevant circuit, event organiser, governing body and race officials.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">3. Third-Party Data</h3>
                <p>
                  My Race Engineer may obtain timing and race information from third-party services and publicly accessible web pages.
                </p>
                <p>
                  We do not guarantee that third-party data will be:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>accurate;</li>
                  <li>complete;</li>
                  <li>current;</li>
                  <li>available at all times; or</li>
                  <li>delivered without interruption.</li>
                </ul>
                <p>
                  The availability and accuracy of My Race Engineer may therefore depend on services outside our control.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">4. Third-Party Services and Websites</h3>
                <p>
                  My Race Engineer may interact with or depend upon third-party services, including timing and race-management platforms.
                </p>
                <p>
                  My Race Engineer is an independent service and is not operated by, endorsed by, sponsored by, or affiliated with Alpha Business Systems Ltd, Alpha Racehub, or any other third-party timing provider unless expressly stated otherwise.
                </p>
                <p>
                  Third-party names, trademarks and logos remain the property of their respective owners.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">5. Availability</h3>
                <p>
                  We aim to keep My Race Engineer available and reliable, but we do not guarantee uninterrupted access.
                </p>
                <p>
                  The service may be unavailable because of:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>maintenance;</li>
                  <li>software updates;</li>
                  <li>network failures;</li>
                  <li>third-party service outages;</li>
                  <li>changes to third-party websites or data;</li>
                  <li>technical failures; or</li>
                  <li>circumstances outside our reasonable control.</li>
                </ul>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">6. Intellectual Property</h3>
                <p>
                  The My Race Engineer software, branding, interface, original content, algorithms and associated materials are owned by or licensed to My Race Engineer unless otherwise stated.
                </p>
                <p>
                  You may not copy, reproduce, modify, redistribute, reverse engineer, resell or commercially exploit My Race Engineer without our permission, except where permitted by law.
                </p>
                <p>
                  Third-party data and content remain the property of their respective owners.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">7. Acceptable Use</h3>
                <p>
                  You must not use My Race Engineer to:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>interfere with the operation of the service;</li>
                  <li>circumvent technical restrictions;</li>
                  <li>attempt to gain unauthorised access;</li>
                  <li>overload or disrupt our systems;</li>
                  <li>reproduce or redistribute the service without permission;</li>
                  <li>use automated systems to abuse the service; or</li>
                  <li>use the service for unlawful purposes.</li>
                </ul>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">8. Changes to the Service</h3>
                <p>
                  We may modify, suspend or discontinue any part of My Race Engineer at any time.
                </p>
                <p>
                  We may also update these Terms when necessary. The latest version will be published on this page.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">9. Limitation of Liability</h3>
                <p>
                  To the maximum extent permitted by law, My Race Engineer and its developers shall not be responsible for losses arising from reliance on inaccurate, delayed or unavailable race information or callouts.
                </p>
                <p>
                  Nothing in these Terms excludes or limits liability where doing so would be unlawful, including liability that cannot legally be excluded under applicable UK law.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">10. Governing Law</h3>
                <p>
                  These Terms are governed by the laws of England and Wales.
                </p>
                <p>
                  Any disputes relating to the service will be subject to the jurisdiction of the courts of England and Wales, unless applicable law requires otherwise.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">11. Contact</h3>
                <p>
                  For questions regarding these Terms, please contact:
                </p>
                <div className="mt-4 space-y-2">
                  <p className="text-[#F4F4F9]">My Race Engineer</p>
                  <p className="text-[#F4F4F9]">Developed by Samuel Williams and Harry Bedford</p>
                  <p className="text-[#D2FF00]">Email: harryjbedford25@gmail.com</p>
                </div>
              </div>
            </div>
          </section>

          <section className="pt-8 border-t border-white/10">
            <h2 className="text-2xl font-semibold mb-4 text-[#F4F4F9]">Privacy Policy</h2>
            <div className="text-[#8E8E93] leading-relaxed space-y-8">
              <p className="font-mono text-[11px] tracking-[0.2em] uppercase text-[#8E8E93]">
                Last updated: 25 August 2026
              </p>

              <p>
                This Privacy Policy explains how My Race Engineer collects, uses and protects personal information.
              </p>

              <p>
                The UK Information Commissioner's Office recommends that privacy notices clearly explain what personal information is collected, why it is used, how long it is retained and who it is shared with.
              </p>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">1. Who We Are</h3>
                <p>
                  My Race Engineer is developed by Samuel Williams and Harry Bedford.
                </p>
                <p>
                  For privacy-related enquiries:
                </p>
                <p className="text-[#D2FF00]">Email: harryjbedford25@gmail.com</p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">2. Information We May Collect</h3>
                <p>
                  Depending on how you use the service, we may collect:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>name or display name;</li>
                  <li>email address;</li>
                  <li>account information;</li>
                  <li>race or session information;</li>
                  <li>device and browser information;</li>
                  <li>IP address;</li>
                  <li>error and diagnostic information;</li>
                  <li>usage information; and</li>
                  <li>information you voluntarily provide to us.</li>
                </ul>
                <p>
                  We will only collect information that is reasonably necessary to operate, maintain and improve the service.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">3. Race Data</h3>
                <p>
                  My Race Engineer may process race information obtained from third-party timing systems.
                </p>
                <p>
                  This may include information such as:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>driver names;</li>
                  <li>race positions;</li>
                  <li>lap times;</li>
                  <li>gaps between drivers;</li>
                  <li>session information; and</li>
                  <li>other publicly displayed race information.</li>
                </ul>
                <p>
                  Where such information relates to an identifiable individual, it may constitute personal data under UK data protection law.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">4. Information Obtained From Third Parties</h3>
                <p>
                  Some information used by My Race Engineer may originate from third-party timing platforms rather than directly from you.
                </p>
                <p>
                  Where personal information is obtained from another source, UK data protection guidance generally requires appropriate privacy information to be provided, subject to applicable exceptions.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">5. How We Use Information</h3>
                <p>
                  We may use information to:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>provide the My Race Engineer service;</li>
                  <li>generate race engineer callouts;</li>
                  <li>maintain accounts;</li>
                  <li>diagnose technical problems;</li>
                  <li>improve the service;</li>
                  <li>prevent abuse;</li>
                  <li>maintain security;</li>
                  <li>understand service usage; and</li>
                  <li>respond to support enquiries.</li>
                </ul>
                <p>
                  We will not sell personal information to third parties.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">6. Legal Basis</h3>
                <p>
                  Where UK GDPR applies, we will process personal data using an appropriate lawful basis, which may include:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>performance of a contract;</li>
                  <li>legitimate interests;</li>
                  <li>consent; or</li>
                  <li>compliance with a legal obligation.</li>
                </ul>
                <p>
                  The appropriate basis depends on the particular processing activity.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">7. Data Retention</h3>
                <p>
                  We will retain personal information only for as long as reasonably necessary for the purpose for which it was collected, unless a longer period is required by law.
                </p>
                <p>
                  Specific retention periods may vary depending on the type of information.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">8. Data Sharing</h3>
                <p>
                  We may use trusted third-party service providers to operate parts of My Race Engineer, such as hosting, authentication, analytics, error monitoring or communications.
                </p>
                <p>
                  Where third parties process personal data on our behalf, we will take reasonable steps to ensure that appropriate contractual and security arrangements are in place.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">9. Security</h3>
                <p>
                  We take reasonable technical and organisational measures to protect personal information against unauthorised access, loss, misuse or disclosure.
                </p>
                <p>
                  However, no internet service can guarantee absolute security.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">10. Your Rights</h3>
                <p>
                  Depending on the circumstances, you may have rights under UK data protection law including the right to:
                </p>
                <ul className="list-disc list-inside space-y-2">
                  <li>access your personal information;</li>
                  <li>request correction;</li>
                  <li>request deletion;</li>
                  <li>restrict processing;</li>
                  <li>object to certain processing;</li>
                  <li>withdraw consent where processing relies on consent; and</li>
                  <li>request data portability.</li>
                </ul>
                <p>
                  More information about privacy rights is available from the Information Commissioner's Office.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">11. Complaints</h3>
                <p>
                  If you have concerns about how we process your personal information, please contact us first at harryjbedford25@gmail.com.
                </p>
                <p>
                  You may also complain to the UK's data protection regulator, the Information Commissioner's Office.
                </p>
              </div>

              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-[#F4F4F9]">12. Changes</h3>
                <p>
                  We may update this Privacy Policy from time to time. The latest version will always be published on this page.
                </p>
              </div>
            </div>
          </section>
        </div>
      </div>
      <Footer />
    </div>
  );
}